language: node_js
node_js:
- 0.11
env:
  global:
  - GH_REF: github.com/ptsurko/persona.git
  - GIT_NAME: Travis-CI
  - GIT_EMAIL: travis@nodemeatspace.com
  - secure: "QTqOvpXoLrVduip14eo6NMtd2Nmo1NzsYTLtcmDyKKEbliY6z+xhSL6dwKuMnODO6c8sXpsqw0HnS/1JZ2dQaYHn+LrQnaAq2BAPwjmFE4FnHEBTiNSAocHuv7kL+2OR1aW88wOP5vQbr4a+9dS6qLP8PfWljRB6qlsXM/q8Zc4="
before_install:
  - chmod +x deploy_ghpages.sh
before_script:
  - npm install -g bower
  - bower install
  - npm install
after_success: ./deploy_ghpages.sh
branches:
  only:
    - master
